// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDg1xBSwmHKV0usIKxTFL5a6fFTb4s3XVM',
    appId: '1:843456771665:web:fb1e3115e9e17ee1582a70',
    messagingSenderId: '843456771665',
    projectId: 'foodking-inilabs',
    authDomain: 'foodking-inilabs.firebaseapp.com',
    storageBucket: 'foodking-inilabs.appspot.com',
    measurementId: 'G-GSJPS921XW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHkY58zN2KjNKUN6fomyXT_c-2c0jXROg',
    appId: '1:843456771665:android:7b1bbf0fa9371c96582a70',
    messagingSenderId: '843456771665',
    projectId: 'foodking-inilabs',
    storageBucket: 'foodking-inilabs.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCO5Sne8yjGu5kRTgf9ivz_iCYn8WA0cU0',
    appId: '1:843456771665:ios:98a7b61b6a0e6d31582a70',
    messagingSenderId: '843456771665',
    projectId: 'foodking-inilabs',
    storageBucket: 'foodking-inilabs.appspot.com',
    androidClientId: '843456771665-6j0q5rbfebo2jf0dlna4bth83genbhb0.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodkingAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCO5Sne8yjGu5kRTgf9ivz_iCYn8WA0cU0',
    appId: '1:843456771665:ios:9c1dc6cca424225b582a70',
    messagingSenderId: '843456771665',
    projectId: 'foodking-inilabs',
    storageBucket: 'foodking-inilabs.appspot.com',
    androidClientId: '843456771665-6j0q5rbfebo2jf0dlna4bth83genbhb0.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodkingAdmin.RunnerTests',
  );
}
